[package]
name = "scx_chaos"
version = "1.0.17"
edition = "2021"
authors = ["Jake Hillion <jake@hillion.co.uk>"]
description = "scx_chaos A general purpose sched_ext scheduler designed to amplify race conditions"
license = "GPL-2.0-only"

[package.metadata.scx]
ci.use_clippy = true

[dependencies]
scx_userspace_arena = "1.0.14"
scx_utils = "1.0.17"
scx_p2dq = "1.0.19"
scx_stats = "1.0.14"
scx_stats_derive = "1.0.14"

anyhow = "1.0.65"
clap = { version = "4.5.28", features = ["derive", "env", "unicode", "wrap_help"] }
crossbeam = "0.8.4"
ctrlc = { version = "3.1", features = ["termination"] }
libbpf-rs = "=0.25.0-beta.1"
libc = "0.2.137"
log = "0.4.17"
nix = { version = "0.29", features = ["process"] }
serde = { version = "1.0.215", features = ["derive"] }
simplelog = "0.12"

[build-dependencies]
scx_utils = "1.0.17"
scx_p2dq = "1.0.19"
